title: Marcelo Andrade.info
author: mfandrade
email: contact@marceloandrade.info
description: > # this means to ignore newlines until "show_exerpts:"
  My simple blog, where I can express a little bit about myself.  Here I write
  down some reference posts like articles or tutorials about technology,
  programming, devops, and stuff like that.  You can also find what I'm
  reading, studying and doing.  Be welcome!
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Marcelo Andrade .info
  tagline: dev, sysadm + life learner
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    github: mfandrade
    linkedIn: in/mfandrade
    facebook: mfandrade1
    twitter: mfandrade
    instagram: quotesmindfulness
    rss: rss
    # dribbble: jekyll
    # flickr:   jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
